language: node_js
node_js:
  - "11"
before_script:
  - npm run lint
  - npm run test
script:
  - npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  skip_cleanup: true
  on:
    tags: true

