language: node_js

node_js:
  - "11"

cache: npm

before_script:
  - npm run bootstrap

jobs:
  include:
    - stage: verify
      script:
        - npm run lint
        - npm run test
    - stage: build
      script: npm run build
    - stage: npm release
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        script: "npm run publish"
        skip_cleanup: true
        on:
          tags: true