name: Verify build

on:
  push:
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - "examples/**"

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT" > "./github.context.json"
          echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run:  |
          echo "$JOB_CONTEXT" > "./job.context.json"
          echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run:  |
          echo "$STEPS_CONTEXT" > "./steps.context.json"
          echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run:  |
          echo "$RUNNER_CONTEXT" > "./runner.context.json"
          echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run:  |
          echo "$STRATEGY_CONTEXT" > "./strategy.context.json"
          echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run:  |
          echo "$MATRIX_CONTEXT" > "./matrix.context.json"
          echo "$MATRIX_CONTEXT"

      - name: Upload all contexts
        uses: actions/upload-artifact@v1
        with:
          name: contexts
          path: "."
          
  verify:
    name: Verify current commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to current repository branch
        uses: actions/checkout@v1

      - name: Read Node.js® version from .nvmrc file
        id: nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Setup locked Node.js® version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmrc.outputs.NVMRC }}"

      - name: Cache Node.js® packages
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install npm dependencies
        run: npm ci

      - name: Check linting
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build plugin
        run: npm run build
