name: Verify build

on: [push]

jobs:
  verify:
    name: Verify current commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to current repository branch
        uses: actions/checkout@v1
      - name: Read Node.js® version from .nvmrc file
        id: nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      - name: Setup locked Node.js® version
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvmrc.outputs.NVMRC }}'
      - name: Install npm root dependencies
        run: npm ci
      - name: Bootstrap all packages in CI mode
        run: npm run bootstrap -- --ci
      - name: Check linting
        run: npm run lint
      - name: Run unit tests
        run: npm test
